apiVersion: labeler.barpilot.io/v1alpha1
kind: Labeler
metadata:
  name: example
  labels:
    operator: node-labeler-operator
spec:
  nodeSelectorTerms:
    - matchExpressions:
        - key: beta.kubernetes.io/os
          operator: In
          values:
            - linux
  merge:
    metadata:
      labels:
        microk8s: "true"
      annotations:
        node-labeler-operator: works
    spec:
      taints:
        - key: dedicated
          value: foo
          effect: PreferNoSchedule
    status:
      capacity:
        example.com/dongle: "4"
        example.com/token: "1"
